// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwdiyfiakgqywdxykgzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3ZGl5Zmlha2dxeXdkeHlrZ3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3OTc5OTYsImV4cCI6MjA3NTM3Mzk5Nn0.p70SKnkV4XMdpWxNUtA0r2tdA5ir9u4mccGUVaM4cFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});